version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqlc
    ports:
      - '3306:3306'
    volumes:
      - ./sqlc/init.sql:/docker-entrypoint-initdb.d/init.sql
