// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Category struct {
	ID   int32
	Name string
}

type Course struct {
	ID         int32
	Name       string
	CategoryID int32
}
