version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
